declare module 'fortmatic'
declare module 'squarelink'
declare module '@walletconnect/web3-provider'
declare module 'web3-provider-engine'
declare module 'web3-provider-engine/subproviders/rpc'
declare module 'web3-provider-engine/subproviders/hooked-wallet'
declare module 'web3-provider-engine/subproviders/subscriptions'
declare module 'web3-provider-engine/subproviders/filters'
declare module 'trezor-connect'
declare module 'eth-lattice-keyring'
declare module 'ethereumjs-tx'
declare module 'ethereumjs-util'
declare module 'hdkey'
declare module '@ledgerhq/hw-app-eth'
declare module '@ledgerhq/hw-transport-u2f'
declare module 'eth-provider'

declare module '@shapeshiftoss/hdwallet-core'
declare module '@shapeshiftoss/hdwallet-keepkey-webusb'

declare module '*.png'
declare module '*.svg'
