export const ADD_CHAINS = 'add_chains'
export const RESET_STORE = 'reset_store'
export const ADD_WALLET = 'add_wallet'
export const UPDATE_WALLET = 'update_wallet'
export const REMOVE_WALLET = 'remove_wallet'
